parser: "@typescript-eslint/parser"
plugins:
  - typescript-sort-keys
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:typescript-sort-keys/recommended
  - prettier
  - react
rules:
  no-console: warn
  semi: error
  "@typescript-eslint/typedef": error
  "@typescript-eslint/no-unused-vars":
    - error
    - varsIgnorePattern: "^_"
  "@typescript-eslint/no-non-null-assertion": error
  "@typescript-eslint/no-explicit-any": error
  "@typescript-eslint/no-unsafe-return": error
  "@typescript-eslint/no-unsafe-assignment": error

parserOptions:
  project: ./tsconfig.json
